server:
    port: 8090
    ribbon:
        eureka:
            enabled: true
spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
            routes:
                - id: mn-first-rest
                  uri: lb://mn-first-rest-balancer/api
                  predicates:
                      - Path=/micro1/api/**
                - id: eureka-client
                  uri: lb://eureka-client
                  predicates:
                  - Path=/eureka-client/**
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        registry-fetch-interval-seconds: 5
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
    instance:
        preferIpAddress: true